# Generated by Django 3.2.25 on 2025-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email id')),
                ('contact_no', models.IntegerField(max_length=10)),
                ('reason', models.TextField(verbose_name='reason')),
            ],
        ),
    ]
